//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentMonitor
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeTable_5
    {
        public string Standard { get; set; }
        public string Days { get; set; }
        public string Period_1 { get; set; }
        public string Period_2 { get; set; }
        public string Period_3 { get; set; }
        public string Period_4 { get; set; }
        public string Period_5 { get; set; }
        public string Period_6 { get; set; }
        public string Period_7 { get; set; }
    }
}
